<a href="https://colab.research.google.com/github/franckbizimana/Wamungu/blob/main/Forbes_Billionaire.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In Class Practice with Pandas

**Data Dictionary**

* Name - Name of the person
* Net worth in billions - Net worth of the person in billions
* Country - Country where the person is from
* Source - Source of the income
* Rank - Rank of the person in the Billionaires list
* Age - Age of the person
* Industry - Industry to which the person is related to

### Importing Pandas Library

In [1]:
import pandas as pd

### Loading the dataset in a pandas dataframe

In [4]:
pd.read_csv('Forbes-list-2020.csv')

,Name,NetWorth in billions,Country,Source,Rank,Age,Industry
0,Jeff Bezos,177.0,United States,Amazon,1,57,Technology
1,Elon Musk,151.0,United States,"Tesla, SpaceX",2,49,Automotive
2,Bernard Arnault & family,150.0,France,LVMH,3,72,Fashion & Retail
3,Bill Gates,124.0,United States,Microsoft,4,65,Technology
4,Mark Zuckerberg,97.0,United States,Facebook,5,36,Technology
...,...,...,...,...,...,...,...
2750,Daniel Yong Zhang,1.0,China,e-commerce,2674,49,Technology
2751,Zhang Yuqiang,1.0,China,Fiberglass,2674,65,Manufacturing
2752,Zhao Meiguang,1.0,China,gold mining,2674,58,Metals & Mining
2753,Zhong Naixiong,1.0,China,conglomerate,2674,58,Diversified
2754,Zhou Wei family,1.0,China,Software,2674,54,Technology

In [2]:
df = pd.read_csv('Forbes-list-2020.csv')

### Print top 5 rows

In [3]:
df.head(5)

,Name,NetWorth in billions,Country,Source,Rank,Age,Industry
0,Jeff Bezos,177.0,United States,Amazon,1,57,Technology
1,Elon Musk,151.0,United States,"Tesla, SpaceX",2,49,Automotive
2,Bernard Arnault & family,150.0,France,LVMH,3,72,Fashion & Retail
3,Bill Gates,124.0,United States,Microsoft,4,65,Technology
4,Mark Zuckerberg,97.0,United States,Facebook,5,36,Technology

In [5]:
df.Age.max()

97

In [7]:
df.iloc[:,[1,2]]

      NetWorth in billions        Country
0                    177.0  United States
1                    151.0  United States
2                    150.0         France
3                    124.0  United States
4                     97.0  United States
...                    ...            ...
2750                   1.0          China
2751                   1.0          China
2752                   1.0          China
2753                   1.0          China
2754                   1.0          China

[2755 rows x 2 columns]

#### <span style="color:crimson">Q1. Whose name is assigned to the 0th index in the dataframe</span>

### Print the dimensions of data

In [6]:
df.shape

(2755, 7)

#### <span style="color:crimson">Q2. How many records do you have in this dataset?</span>

### Datatypes of all the fields in the data

In [8]:
type(df)

pandas.core.frame.DataFrame

#### <span style="color:crimson">Q3. What is the data type of the variable Source</span>

### Checking for missing values

In [12]:
df.isnull().sum()

Name                    0
NetWorth in billions    0
Country                 0
Source                  0
Rank                    0
Age                     0
Industry                0
dtype: int64

#### <span style="color:crimson">Q4. How many missing values exists in the industry feature</span>

### Print the basic stats for this dataset

In [13]:
df.describe()

       NetWorth in billions         Rank          Age
count           2755.000000  2755.000000  2755.000000
mean               4.749220  1345.663521    63.014519
std                9.615358   772.669811    13.259017
min                1.000000     1.000000    18.000000
25%                1.500000   680.000000    54.000000
50%                2.300000  1362.000000    62.000000
75%                4.200000  2035.000000    72.000000
max              177.000000  2674.000000    97.000000

#### <span style="color:crimson">Q5. Who is the yongest billionare in this list?</span>

940	Kevin David Lehmann	3.3	Germany	drugstores	925	18	Fashion & Retail

### Sort the dataset  by Age (ascending) and reset the index

In [24]:
df.sort_values(by='Age',ascending=True,inplace=True)
df

,Name,NetWorth in billions,Country,Source,Rank,Age,Industry
940,Kevin David Lehmann,3.3,Germany,drugstores,925,18,Fashion & Retail
2143,Alexandra Andresen,1.4,Norway,investments,2141,24,Diversified
2122,Wang Zelong,1.5,China,chemicals,2035,24,Metals & Mining
2144,Katharina Andresen,1.4,Norway,investments,2141,25,Diversified
1338,Austin Russell,2.4,United States,Unknown,1299,26,Automotive
...,...,...,...,...,...,...,...
729,Masatoshi Ito,4.0,Japan,retail,727,96,Fashion & Retail
1579,S. Daniel Abraham,2.0,United States,Slim-Fast,1580,96,Food & Beverage
1626,Charles Munger,2.0,United States,Berkshire Hathaway,1580,97,Finance & Investments
1559,David Murdock,2.1,United States,"Dole, real estate",1517,97,Food & Beverage
170,Robert Kuok,12.6,Malaysia,"palm oil, shipping, property",171,97,Diversified

In [26]:
# run
df.iloc[1200,3]

'alcoholic beverages'

#### <span style="color:crimson">Q6. What is the output of `df.iloc[1200,3]`?</span>

alcoholic beverages

### Create a new column `Year_of_birth`
Note: The dataset is from the year 2020. The age of those Billionaires is as of 2020.

In [27]:
# create a new column 'Year_of_birth'
df['Year_of_birth'] = 2020 - df['Age']
df

,Name,NetWorth in billions,Country,Source,Rank,Age,Industry,Year_of_birth
940,Kevin David Lehmann,3.3,Germany,drugstores,925,18,Fashion & Retail,2002
2143,Alexandra Andresen,1.4,Norway,investments,2141,24,Diversified,1996
2122,Wang Zelong,1.5,China,chemicals,2035,24,Metals & Mining,1996
2144,Katharina Andresen,1.4,Norway,investments,2141,25,Diversified,1995
1338,Austin Russell,2.4,United States,Unknown,1299,26,Automotive,1994
...,...,...,...,...,...,...,...,...
729,Masatoshi Ito,4.0,Japan,retail,727,96,Fashion & Retail,1924
1579,S. Daniel Abraham,2.0,United States,Slim-Fast,1580,96,Food & Beverage,1924
1626,Charles Munger,2.0,United States,Berkshire Hathaway,1580,97,Finance & Investments,1923
1559,David Murdock,2.1,United States,"Dole, real estate",1517,97,Food & Beverage,1923
170,Robert Kuok,12.6,Malaysia,"palm oil, shipping, property",171,97,Diversified,1923

In [28]:
#view the data
df.head()

,Name,NetWorth in billions,Country,Source,Rank,Age,Industry,Year_of_birth
940,Kevin David Lehmann,3.3,Germany,drugstores,925,18,Fashion & Retail,2002
2143,Alexandra Andresen,1.4,Norway,investments,2141,24,Diversified,1996
2122,Wang Zelong,1.5,China,chemicals,2035,24,Metals & Mining,1996
2144,Katharina Andresen,1.4,Norway,investments,2141,25,Diversified,1995
1338,Austin Russell,2.4,United States,Unknown,1299,26,Automotive,1994

### Select Billionaires born in 1996

In [35]:
# Using where condition
df.where(df['Year_of_birth']==1996 )
df

,Name,NetWorth in billions,Country,Source,Rank,Age,Industry,Year_of_birth
940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2143,Alexandra Andresen,1.4,Norway,investments,2141.0,24.0,Diversified,1996.0
2122,Wang Zelong,1.5,China,chemicals,2035.0,24.0,Metals & Mining,1996.0
2144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
729,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df.where(df['Year_of_birth']==1996 )
df.notnull().sum()

Name                    2
NetWorth in billions    2
Country                 2
Source                  2
Rank                    2
Age                     2
Industry                2
Year_of_birth           2
dtype: int64

#### <span style="color:crimson">Q7. How many Billionaires were born in 1996?</span>

In [38]:
df.where(df['Year_of_birth']==1996 ).count()

Name                    2
NetWorth in billions    2
Country                 2
Source                  2
Rank                    2
Age                     2
Industry                2
Year_of_birth           2
dtype: int64